import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { StrategicReport } from '../types';

export const exportReportToPDF = async (report: StrategicReport) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Create a temporary container for rendering
  const container = document.createElement('div');
  container.style.width = '190mm'; // A4 width minus margins
  container.style.padding = '20mm';
  container.style.color = '#000';
  container.style.backgroundColor = '#fff';
  container.style.fontFamily = '"Inter", "PingFang SC", "Microsoft YaHei", sans-serif';
  container.style.position = 'absolute';
  container.style.left = '-9999px';
  container.style.top = '-9999px';
  
  // Build the report HTML content
  let htmlContent = `
    <div style="text-align: center; margin-bottom: 50px; padding-top: 50px;">
      <h1 style="font-size: 28pt; margin-bottom: 20px;">${report.title}</h1>
      <p style="font-size: 14pt; font-style: italic; color: #666;">Strategic Analysis & Synthesis Report</p>
      <p style="font-size: 12pt; color: #888;">Generated by VEDA Arch-Academic Core</p>
      <p style="font-size: 10pt; color: #aaa;">${new Date().toLocaleDateString()}</p>
    </div>
    
    <div style="margin-top: 50px;">
      <h2 style="font-size: 18pt; border-bottom: 1px solid #eee; padding-bottom: 10px;">Table of Contents</h2>
      <ul style="list-style: none; padding-left: 0;">
        ${report.outline.map((sec, idx) => `
          <li style="margin-bottom: 10px; font-size: 12pt;">
            <span style="font-weight: bold; margin-right: 10px;">${idx + 1}.</span> ${sec.title}
          </li>
        `).join('')}
      </ul>
    </div>
  `;

  // Add sections
  report.outline.forEach((sec, idx) => {
    if (!sec.content) return;
    
    // Simple markdown to HTML conversion for the PDF
    const cleanContent = sec.content
      .replace(/^### (.*$)/gim, '<h3 style="font-size: 14pt; margin-top: 20px;">$1</h3>')
      .replace(/^## (.*$)/gim, '<h2 style="font-size: 16pt; margin-top: 25px; border-bottom: 1px solid #eee;">$1</h2>')
      .replace(/^# (.*$)/gim, '<h1 style="font-size: 20pt; margin-top: 30px;">$1</h1>')
      .replace(/\*\*(.*)\*\*/gim, '<strong>$1</strong>')
      .replace(/\*(.*)\*/gim, '<em>$1</em>')
      .replace(/\n/g, '<br/>');

    htmlContent += `
      <div style="page-break-before: always; margin-top: 40px;">
        <h2 style="font-size: 18pt; color: #222; margin-bottom: 20px;">${idx + 1}. ${sec.title}</h2>
        <div style="font-size: 11pt; line-height: 1.6; color: #444; text-align: justify;">
          ${cleanContent}
        </div>
      </div>
    `;
  });

  container.innerHTML = htmlContent;
  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff'
    });
    
    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const imgWidth = 190;
    const pageHeight = 287; // A4 height - margins
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    
    let heightLeft = imgHeight;
    let position = 0;

    doc.addImage(imgData, 'JPEG', 10, 5, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      doc.addPage();
      doc.addImage(imgData, 'JPEG', 10, position + 5, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    doc.save(`${report.title.replace(/\s+/g, '_')}_strategic_report.pdf`);
    document.body.removeChild(container);
  } catch (error) {
    console.error("PDF generation failed:", error);
    // Fallback to basic jspdf if html conversion fails
    doc.text("PDF Generation Error. Please use browser print (Ctrl+P) for best results.", 10, 10);
    doc.save("report_error.pdf");
    document.body.removeChild(container);
  }
};
